<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="WIN-96UQTP4SIUT"><DocLocation><![CDATA[C:\Users\LiuZhuo\Desktop\Excel]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Excel]]></DName>
<Res><![CDATA[Res25]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:05]]></Time>
<TimeTick>1481618645</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:05]]></Time>
<TimeTick>1481618645</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:06]]></Time>
<TimeTick>1481618646</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["zhangjiaming"]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:12]]></Time>
<TimeTick>1481618652</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ userpwd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lzjm12345"]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:13]]></Time>
<TimeTick>1481618653</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ userpwd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ 登录 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:13]]></Time>
<TimeTick>1481618653</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 登录 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ 退出  ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", "退出", "退出 ", 20000]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:33]]></Time>
<TimeTick>1481618673</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 退出  ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:34]]></Time>
<TimeTick>1481618674</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:36]]></Time>
<TimeTick>1481618676</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:36]]></Time>
<TimeTick>1481618676</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:41]]></Time>
<TimeTick>1481618681</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["llllllllg"]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:42]]></Time>
<TimeTick>1481618682</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ userpwd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lzjm12345"]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:42]]></Time>
<TimeTick>1481618682</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ userpwd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ 登录 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:44:43]]></Time>
<TimeTick>1481618683</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 登录 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Link ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", "退出", 20000]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:04]]></Time>
<TimeTick>1481618704</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Link ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:05]]></Time>
<TimeTick>1481618705</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:06]]></Time>
<TimeTick>1481618706</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:06]]></Time>
<TimeTick>1481618706</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="82" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="81" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:11]]></Time>
<TimeTick>1481618711</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="85" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["eeeeeeeeeee"]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:12]]></Time>
<TimeTick>1481618712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ userpwd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["eeeeeeeee"]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:13]]></Time>
<TimeTick>1481618713</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="90" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ userpwd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ 登录 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:13]]></Time>
<TimeTick>1481618713</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 登录 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Link ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", "退出", 20000]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:34]]></Time>
<TimeTick>1481618734</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="130" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Link ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/13 - 16:45:35]]></Time>
<TimeTick>1481618735</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/12/13 - 16:44:04" eTime="2016/12/13 - 16:45:35" passed="3" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[Excel Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2016/12/13 - 16:43:57" eTime="2016/12/13 - 16:45:36" passed="3" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test Excel Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>