<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="WIN-96UQTP4SIUT"><DocLocation><![CDATA[C:\Users\LiuZhuo\Desktop\Setto]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Setto]]></DName>
<Res><![CDATA[Res12]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/12/15 - 9:15:56]]></Time>
<TimeTick>1481764556</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Details>
<Time><![CDATA[2016/12/15 - 9:15:56]]></Time>
<TimeTick>1481764556</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:00]]></Time>
<TimeTick>1481764560</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["zhangjiaming"]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:00]]></Time>
<TimeTick>1481764560</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ userpwd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lzjm12345"]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:00]]></Time>
<TimeTick>1481764560</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ userpwd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ 登录 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:00]]></Time>
<TimeTick>1481764560</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 登录 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:03]]></Time>
<TimeTick>1481764563</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ fname ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["鱼香肉丝"]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:03]]></Time>
<TimeTick>1481764563</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ fname ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ 搜索 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:03]]></Time>
<TimeTick>1481764563</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 搜索 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ 购物车  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:11]]></Time>
<TimeTick>1481764571</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 购物车  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ WebCheckBox ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "[ WebCheckBox ]" (of class WebCheckBox). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:33]]></Time>
<TimeTick>1481764593</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ WebCheckBox ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = checkbox<br>Name = input[]<br>Mercury Class = WebCheckBox<br>Html Tag = INPUT<br>DHTML Class = in<br>]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:33]]></Time>
<TimeTick>1481764593</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" status="Warning" nType="Description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebCheckBox ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="73" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebCheckBox ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;[ WebCheckBox ]&quot; (of class WebCheckBox). Verify that this object's properties match an object currently displayed in your application.<BR>Line (52): &quot;.WebCheckBox(objInput).Set &quot;ON&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:33]]></Time>
<TimeTick>1481764593</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" status="Failed" Source="Action1" SourceLine="51" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/12/15 - 9:16:41]]></Time>
<TimeTick>1481764601</TimeTick>
<NodeArgs eType="General" icon="12" nRep="76" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/12/15 - 9:15:55" eTime="2016/12/15 - 9:16:41" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Setto Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2016/12/15 - 9:15:53" eTime="2016/12/15 - 9:16:41" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Setto Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>