<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="WIN-96UQTP4SIUT"><DocLocation><![CDATA[C:\Users\LiuZhuo\Desktop\Setto]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Setto]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/12/15 - 8:12:51]]></Time>
<TimeTick>1481760771</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Details>
<Time><![CDATA[2016/12/15 - 8:12:51]]></Time>
<TimeTick>1481760771</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "http://10.7.90.13:8032/MS/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:15]]></Time>
<TimeTick>1481760795</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["zhangjiaming"]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:17]]></Time>
<TimeTick>1481760797</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ userpwd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lzjm12345"]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:18]]></Time>
<TimeTick>1481760798</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ userpwd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ 登录 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:18]]></Time>
<TimeTick>1481760798</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 登录 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ dcms ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:18]]></Time>
<TimeTick>1481760798</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ dcms ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ fname ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["鱼香肉丝"]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:18]]></Time>
<TimeTick>1481760798</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ fname ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ 搜索 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:18]]></Time>
<TimeTick>1481760798</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 搜索 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[dcms_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:44]]></Time>
<TimeTick>1481760824</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[dcms]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:44]]></Time>
<TimeTick>1481760824</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["+购物车"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:44]]></Time>
<TimeTick>1481760824</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["+购物车"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["+购物车"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>outertext=+购物车<br>micclass=WebElement<br>innertext=AddCarts<br>innerhtml=+购物车<br>html tag=A<br>class=addCarts<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (18 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 18 matches)</SPAN><br>class=addCarts<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=AddCarts<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:44]]></Time>
<TimeTick>1481760824</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="79" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["+购物车"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[+购物车.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:44]]></Time>
<TimeTick>1481760824</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="80" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[+购物车.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ 购物车  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/15 - 8:13:53]]></Time>
<TimeTick>1481760833</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="83" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 购物车  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ WebCheckBox ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "[ WebCheckBox ]" (of class WebCheckBox). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/12/15 - 8:14:15]]></Time>
<TimeTick>1481760855</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebCheckBox ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = checkbox<br>Name = input[]<br>Mercury Class = WebCheckBox<br>htnl tag = INPUT<br>]]></Details>
<Time><![CDATA[2016/12/15 - 8:14:15]]></Time>
<TimeTick>1481760855</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="126" status="Warning" nType="Description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebCheckBox ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="125" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebCheckBox ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="77" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[dcms]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="76" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[dcms_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;[ WebCheckBox ]&quot; (of class WebCheckBox). Verify that this object's properties match an object currently displayed in your application.<BR>Line (1): &quot;systemUtil.Run &quot;http://10.7.90.13:8032/MS/&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/12/15 - 8:14:15]]></Time>
<TimeTick>1481760855</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="127" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/12/15 - 8:14:20]]></Time>
<TimeTick>1481760860</TimeTick>
<NodeArgs eType="General" icon="15" nRep="128" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/12/15 - 8:12:49" eTime="2016/12/15 - 8:14:20" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Setto Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2016/12/15 - 8:12:46" eTime="2016/12/15 - 8:14:21" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Setto Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>