<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="10.00" os="" host="YANG-PC"><DocLocation><![CDATA[C:\Users\yang\Desktop\test6]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[test6]]></DName>
<Res><![CDATA[Res43]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:39]]></Time>
<TimeTick>1482129879</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://10.7.90.2:8032/MS/admin.php/Index/index]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:39]]></Time>
<TimeTick>1482129879</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" nType="Navigate to http://10.7.90.2:8032/MS/admin.php/Index/index" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:40]]></Time>
<TimeTick>1482129880</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Dcms管理 ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:40]]></Time>
<TimeTick>1482129880</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Dcms管理 ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:42]]></Time>
<TimeTick>1482129882</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ userpwd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:42]]></Time>
<TimeTick>1482129882</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ userpwd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ SUBMIT ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:42]]></Time>
<TimeTick>1482129882</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ SUBMIT ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ 美食管理 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:44]]></Time>
<TimeTick>1482129884</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 美食管理 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ 添加 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:45]]></Time>
<TimeTick>1482129885</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ 添加 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ name ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["西红柿炒鸡蛋"]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:49]]></Time>
<TimeTick>1482129889</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ name ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ price ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["20"]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:51]]></Time>
<TimeTick>1482129891</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ price ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ orderno ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:55]]></Time>
<TimeTick>1482129895</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ orderno ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ cid ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["东北风味"]]></Details>
<Time><![CDATA[2016/12/19 - 14:44:58]]></Time>
<TimeTick>1482129898</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ cid ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/12/19 - 14:45:12]]></Time>
<TimeTick>1482129912</TimeTick>
<NodeArgs eType="General" icon="10" nRep="87" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/12/19 - 14:44:40" eTime="2016/12/19 - 14:45:12" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[test6 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/12/19 - 14:45:13]]></Time>
<TimeTick>1482129913</TimeTick>
<NodeArgs eType="General" icon="11" nRep="90" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/12/19 - 14:44:38" eTime="2016/12/19 - 14:45:13" passed="0" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test test6 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>